name: Test Node with workflow
on: push

jobs:
  first-job:
    name: Build with Node
    runs-on: ubuntu-latest
    container: node:18  # Use supported LTS version
    steps:
      - name: Show Node and NPM versions
        run: |
          node --version
          npm --version

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run App
        run: node index.js
